## - http
cluster.name: docker-cluster
network.host: 0.0.0.0
xpack.license.self_generated.type: trial
xpack.security.enabled: true
bootstrap.memory_lock: true
path.data: /usr/share/elasticsearch/data

# xpack.security.http.ssl.enabled: true
# xpack.security.http.ssl.key: elasticsearch.key
# xpack.security.http.ssl.certificate: elasticsearch.crt
# xpack.security.http.ssl.certificate_authorities: ca.crt
# xpack.security.http.ssl.client_authentication: optional