version: '3.8'
services:
    # Todo: 1. Service Search
    service_search:
        container_name: service_search
        depends_on:
            - elastic-search
            - kibana
        restart: always
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        environment:
            - NODE_ENV=${NODE_ENV}
        ports:
            - ${PORT}:${PORT}
        volumes:
            - './src:/usr/src/app/src'
        env_file:
            - .env
        command: yarn dev
        networks:
            - service_search_service-network

    # Todo: 2. Elastic search
    elastic-search:
        container_name: elastic-search
        image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
        environment:
            - xpack.security.enabled=false
            - 'discovery.type=single-node'
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        ports:
            - ${ELASTIC_SEARCH_PORT}:${ELASTIC_SEARCH_PORT}
        env_file:
            - .env
        networks:
            - service_search_service-network

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:8.4.3
        depends_on:
            - elastic-search
        environment:
            - ELASTICSEARCH_HOSTS=${ELASTIC_SEARCH_HOST}
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        cap_add:
            - IPC_LOCK
        ports:
            - ${KIBANA_PORT}:${KIBANA_PORT}
        env_file:
            - .env
        networks:
            - service_search_service-network
networks:
    service_search_service-network:
        driver: bridge

volumes:
    elasticsearch-data:
        driver: local
